// Generated by scripts/build-style-map.mjs — styles for MlCheckboxGroup.
import '../core.css'
import '../components/field.css'
import '../components/checkbox.css'
import '../components/paw.css'
import '../components/form.css'
import '../components/checkbox-group.css'
