// Generated by scripts/build-style-map.mjs — styles for MlComments.
import '../core.css'
import '../components/avatar.css'
import '../components/paw.css'
import '../components/mascot.css'
import '../components/empty-upload.css'
import '../components/comments.css'
