// Generated by scripts/build-style-map.mjs — styles for MlGacha.
import '../core.css'
import '../components/paw.css'
import '../components/effects.css'
import '../components/cute-icon.css'
import '../components/gacha.css'
