// Generated by scripts/build-style-map.mjs — styles for MlInbox.
import '../core.css'
import '../components/avatar.css'
import '../components/paw.css'
import '../components/mascot.css'
import '../components/empty-upload.css'
import '../components/cute-icon.css'
import '../components/inbox.css'
