// Generated by scripts/build-style-map.mjs — styles for MlInvoiceChecker.
import '../core.css'
import '../components/field.css'
import '../components/paw.css'
import '../components/form.css'
import '../components/effects.css'
import '../components/inputs-extra.css'
import '../components/cute-icon.css'
import '../components/invoice.css'
