// Generated by scripts/build-style-map.mjs — styles for MlInfiniteScroll.
import '../core.css'
import '../components/button.css'
import '../components/loader.css'
import '../components/paw.css'
import '../components/effects.css'
import '../components/layout.css'
