// Generated by scripts/build-style-map.mjs — styles for MlSwipeStack.
import '../core.css'
import '../components/paw.css'
import '../components/mascot.css'
import '../components/empty-upload.css'
import '../components/cute-icon.css'
import '../components/swipe-stack.css'
import '../components/pull-swipe.css'
