// Generated by scripts/build-style-map.mjs — styles for MlTagInput.
import '../core.css'
import '../components/field.css'
import '../components/paw.css'
import '../components/calendar.css'
import '../components/combobox.css'
import '../components/form.css'
import '../components/inputs-extra.css'
