// Generated by scripts/build-style-map.mjs — styles for MlTable.
import '../core.css'
import '../components/checkbox.css'
import '../components/loader.css'
import '../components/paw.css'
import '../components/table.css'
import '../components/navigation.css'
