// Generated by scripts/build-style-map.mjs — styles for MlText.
import '../core.css'
import '../components/button.css'
import '../components/paw.css'
import '../components/effects.css'
import '../components/copy-button.css'
import '../components/typography.css'
