// Generated by scripts/build-style-map.mjs — styles for MlTour.
import '../core.css'
import '../components/button.css'
import '../components/paw.css'
import '../components/mascot.css'
import '../components/effects.css'
import '../components/tour.css'
