// Generated by scripts/build-style-map.mjs — styles for MlTransfer.
import '../core.css'
import '../components/button.css'
import '../components/checkbox.css'
import '../components/paw.css'
import '../components/transfer.css'
import '../components/effects.css'
