// Generated by scripts/build-style-map.mjs — styles for MlUpload.
import '../core.css'
import '../components/paw.css'
import '../components/empty-upload.css'
import '../components/skeleton.css'
import '../components/image.css'
