// Regenerate src/globe-data.ts — the land mask MlGlobe / Globe draw as dots.
//   node scripts/build-globe.mjs              download the pinned source and rewrite
//   node scripts/build-globe.mjs file.json    use a local copy instead
//
// Source: world-atlas 2.0.2 land-50m.json (ISC, https://github.com/topojson/world-atlas),
// a TopoJSON build of Natural Earth's 1:50m land polygons (public domain, naturalearthdata.com).
//
// Pipeline (no dependencies): decode the TopoJSON arcs → test each point of a
// Fibonacci sphere (evenly spread, no crowding at the poles) for land with an
// even–odd ray cast in lon/lat → pack the answers into a bitset → base64.
// The component rebuilds the same sphere at runtime, so only the bits ship.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const SOURCE = 'https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/land-50m.json'
const target = fileURLToPath(new URL('../src/globe-data.ts', import.meta.url))

/** Points on the sphere; keep in step with globeSpherePoint() in src/components/globe.ts. */
const COUNT = 16000
const GOLDEN = Math.PI * (3 - Math.sqrt(5))

const args = process.argv.slice(2)
const topo = JSON.parse(args[0] ? readFileSync(args[0], 'utf8') : await (await fetch(SOURCE)).text())

/* ── TopoJSON → rings of [lon, lat] ─────────────────────── */
const [sx, sy] = topo.transform.scale
const [tx, ty] = topo.transform.translate
const arcs = topo.arcs.map((arc) => {
  let x = 0
  let y = 0
  return arc.map(([dx, dy]) => [(x += dx) * sx + tx, (y += dy) * sy + ty])
})
const arcPoints = (i) => (i >= 0 ? arcs[i] : arcs[~i].slice().reverse())
const ring = (ids) => ids.flatMap((id, k) => (k ? arcPoints(id).slice(1) : arcPoints(id)))

const rings = []
const collect = (geom) => {
  if (geom.type === 'GeometryCollection') geom.geometries.forEach(collect)
  else if (geom.type === 'Polygon') geom.arcs.forEach((r) => rings.push(ring(r)))
  else if (geom.type === 'MultiPolygon') geom.arcs.forEach((p) => p.forEach((r) => rings.push(ring(r))))
}
collect(topo.objects.land)

// Bounding boxes make the ray cast cheap.
const boxed = rings.map((r) => {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity
  for (const [x, y] of r) {
    if (x < x0) x0 = x
    if (x > x1) x1 = x
    if (y < y0) y0 = y
    if (y > y1) y1 = y
  }
  return { r, x0, y0, x1, y1 }
})

function isLand(lon, lat) {
  let inside = false
  for (const { r, x0, y0, x1, y1 } of boxed) {
    // Antarctica's ring runs along the pole, so anything south of its coast is inside it.
    if (lon < x0 || lon > x1 || lat > y1 || (lat < y0 && y0 > -89)) continue
    for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
      const [xi, yi] = r[i]
      const [xj, yj] = r[j]
      if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside
    }
  }
  return inside
}

/* ── Sphere → bitset ────────────────────────────────────── */
const bytes = new Uint8Array(Math.ceil(COUNT / 8))
let land = 0
for (let i = 0; i < COUNT; i++) {
  const y = 1 - ((i + 0.5) * 2) / COUNT
  const lat = (Math.asin(y) * 180) / Math.PI
  let lon = ((GOLDEN * i * 180) / Math.PI) % 360
  if (lon > 180) lon -= 360
  if (isLand(lon, lat)) {
    bytes[i >> 3] |= 1 << (i & 7)
    land++
  }
}

const out = `// Generated by scripts/build-globe.mjs — do not edit.
// Land mask for MlGlobe / Globe: bit i is set when point i of a ${COUNT}-point
// Fibonacci sphere falls on land (${land} points).
// Natural Earth 1:50m land (public domain) via world-atlas 2.0.2 (ISC).

export const GLOBE_POINT_COUNT = ${COUNT}

export const GLOBE_LAND_BITS =
  '${Buffer.from(bytes).toString('base64')}'
`
writeFileSync(target, out)
console.log(`globe-data: ${land} / ${COUNT} land points, ${out.length} bytes`)
