// The React components' props, generated by the docs-react-api plugin in vite.config.ts.
declare module 'virtual:react-api' {
  import type { ReactApi } from './react-docs'

  const data: { props: ReactApi; components: string[] }
  export default data
}

// Docs examples converted to React — only the verified ones (see tests/react/examples.test.tsx).
declare module 'virtual:react-examples' {
  const examples: Record<string, { tsx: string; css: string }>
  export default examples
}
